# Generated by Django 4.1.7 on 2023-07-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbooking',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Flightbooking',
        ),
    ]
