# Generated by Django 4.1.7 on 2023-07-23 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0002_remove_flightbooking_name_remove_flightbooking_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('upadate_at', models.DateField(auto_now_add=True)),
                ('From', models.CharField(blank=True, max_length=100, null=True)),
                ('to', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('f_date', models.DateField()),
                ('adult', models.IntegerField(default=0)),
                ('child', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flightbooking',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('upadate_at', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('Class', models.CharField(choices=[('Econnamy', 'Econnamy'), ('Bussines', 'Bussines')], max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('booking_type', models.CharField(choices=[('Status', 'Success'), ('Status', 'Failed')], max_length=100)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_booking', to='travel.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
