# Generated by Django 4.1.7 on 2023-07-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_flightbooking_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='booking_type',
            field=models.BooleanField(),
        ),
    ]
